version: "3.7"
services:
  erd-viewer:
    build:
      context: .
    image: erd-viewer:latest
    volumes:
      - ./data:/usr/erd-viewer/data:ro,z
    expose:
      - 3031/tcp
    depends_on:
      - redis

  nginx:
    image: nginx:alpine
    volumes:
      - ./configs/nginx_uwsgi.conf:/etc/nginx/conf.d/default.conf:ro,z
      - ./web:/usr/share/nginx/html:ro,z
    ports:
      - 4444:80/tcp
    depends_on:
      - erd-viewer

  redis:
    image: redis:alpine
    expose:
      - 6379/tcp
