version: "3.7"
services:
  erd-viewer:
    build:
      context: .
      dockerfile: ./docker-compose/Dockerfile
    image: erd-viewer:latest
    volumes:
      - ./data:/usr/erd-viewer/data:ro,z
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    expose:
      - 3031/tcp
    depends_on:
      - redis

  nginx:
    build:
      context: .
      dockerfile: ./docker-compose/nginx/Dockerfile
    image: erd-viewer_nginx:latest
    ports:
      - 4444:80/tcp
    depends_on:
      - redis
      - erd-viewer

  redis:
    build:
      context: .
      dockerfile: ./docker-compose/redis/Dockerfile
    image: erd-viewer_redis:latest
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
