version: "3.7"
services:
  erd-viewer:
    build:
      context: .
    image: erd-viewer:latest
    volumes:
      - ./data:/usr/erd-viewer/data:ro,z
    expose:
      - 3031/tcp
    depends_on:
      - redis

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    image: erd-viewer_nginx:latest
    ports:
      - 4444:80/tcp
    depends_on:
      - redis
      - erd-viewer

  redis:
    build:
      context: .
      dockerfile: ./redis/Dockerfile
    image: erd-viewer_redis:latest
    expose:
      - 6379/tcp
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
